import { FilterSection } from './operator-api';

export const FILTER_SECTIONS: FilterSection[] = [
  {
    key: 'class',
    field: 'class',
    label: 'Class',
    options: [
      { label: 'Caster', value: 'Caster' },
      { label: 'Defender', value: 'Defender' },
      { label: 'Guard', value: 'Guard' },
      { label: 'Medic', value: 'Medic' },
      { label: 'Sniper', value: 'Sniper' },
      { label: 'Specialist', value: 'Specialist' },
      { label: 'Supporter', value: 'Supporter' },
      { label: 'Vanguard', value: 'Vanguard' },
    ],
  },
  {
    key: 'branch',
    field: 'branch',
    label: 'Branch',
    options: [
      { label: 'Abjurer', value: 'Abjurer' },
      { label: 'Agent', value: 'Agent' },
      { label: 'Alchemist', value: 'Alchemist' },
      { label: 'Ambusher', value: 'Ambusher' },
      { label: 'Artificer', value: 'Artificer' },
      { label: 'Artilleryman', value: 'Artilleryman' },
      { label: 'Arts Fighter', value: 'Arts Fighter' },
      { label: 'Arts Protector', value: 'Arts Protector' },
      { label: 'Bard', value: 'Bard' },
      { label: 'Besieger', value: 'Besieger' },
      { label: 'Blast', value: 'Blast' },
      { label: 'Centurion', value: 'Centurion' },
      { label: 'Chain', value: 'Chain' },
      { label: 'Charger', value: 'Charger' },
      { label: 'Core', value: 'Core' },
      { label: 'Crusher', value: 'Crusher' },
      { label: 'Deadeye', value: 'Deadeye' },
      { label: 'Decel Binder', value: 'Decel Binder' },
      { label: 'Dollkeeper', value: 'Dollkeeper' },
      { label: 'Dreadnought', value: 'Dreadnought' },
      { label: 'Duelist', value: 'Duelist' },
      { label: 'Earthshaker', value: 'Earthshaker' },
      { label: 'Executor', value: 'Executor' },
      { label: 'Fighter', value: 'Fighter' },
      { label: 'Flinger', value: 'Flinger' },
      { label: 'Fortress', value: 'Fortress' },
      { label: 'Geek', value: 'Geek' },
      { label: 'Guardian', value: 'Guardian' },
      { label: 'Heavyshooter', value: 'Heavyshooter' },
      { label: 'Hexer', value: 'Hexer' },
      { label: 'Hookmaster', value: 'Hookmaster' },
      { label: 'Hunter', value: 'Hunter' },
      { label: 'Incantation', value: 'Incantation' },
      { label: 'Instructor', value: 'Instructor' },
      { label: 'Juggernaut', value: 'Juggernaut' },
      { label: 'Liberator', value: 'Liberator' },
      { label: 'Loopshooter', value: 'Loopshooter' },
      { label: 'Lord', value: 'Lord' },
      { label: 'Marksman', value: 'Marksman' },
      { label: 'Mech-Accord', value: 'Mech-Accord' },
      { label: 'Medic', value: 'Medic' },
      { label: 'Mercenary', value: 'Mercenary' },
      { label: 'Merchant', value: 'Merchant' },
      { label: 'Multi-target', value: 'Multi-target' },
      { label: 'Mystic', value: 'Mystic' },
      { label: 'Phalanx', value: 'Phalanx' },
      { label: 'Pioneer', value: 'Pioneer' },
      { label: 'Primal', value: 'Primal' },
      { label: 'Primal Protector', value: 'Primal Protector' },
      { label: 'Protector', value: 'Protector' },
      { label: 'Push Stroker', value: 'Push Stroker' },
      { label: 'Reaper', value: 'Reaper' },
      { label: 'Ritualist', value: 'Ritualist' },
      { label: 'Sentry Protector', value: 'Sentry Protector' },
      { label: 'Shaper', value: 'Shaper' },
      { label: 'Skybreaker', value: 'Skybreaker' },
      { label: 'Skyranger', value: 'Skyranger' },
      { label: 'Soloblade', value: 'Soloblade' },
      { label: 'Splash', value: 'Splash' },
      { label: 'Spreadshooter', value: 'Spreadshooter' },
      { label: 'Standard Bearer', value: 'Standard Bearer' },
      { label: 'Strategist', value: 'Strategist' },
      { label: 'Summoner', value: 'Summoner' },
      { label: 'Swordmaster', value: 'Swordmaster' },
      { label: 'Tactician', value: 'Tactician' },
      { label: 'Therapist', value: 'Therapist' },
      { label: 'Trapmaster', value: 'Trapmaster' },
      { label: 'Wandering', value: 'Wandering' },
      { label: 'Watchman', value: 'Watchman' },
    ],
  },
  {
    key: 'position',
    field: 'position',
    label: 'Position',
    options: [
      { label: 'Melee', value: 'Melee' },
      { label: 'Ranged', value: 'Ranged' },
    ],
  },
  {
    key: 'rarity',
    field: 'rarity',
    label: 'Rarity',
    options: [
      { label: '1', value: '1' },
      { label: '2', value: '2' },
      { label: '3', value: '3' },
      { label: '4', value: '4' },
      { label: '5', value: '5' },
      { label: '6', value: '6' },
    ],
  },
  {
    key: 'gender',
    field: 'gender',
    label: 'Gender',
    options: [
      { label: 'Conviction', value: 'Conviction' },
      { label: 'Female', value: 'Female' },
      { label: 'Lady', value: 'Lady' },
      { label: 'Male', value: 'Male' },
      { label: 'Unknown', value: 'Unknown' },
    ],
  },
  {
    key: 'infection_status',
    field: 'infection_status',
    label: 'Infection Status',
    options: [
      { label: 'infected', value: 'infected' },
      { label: 'not_infected', value: 'not_infected' },
      { label: 'unknown', value: 'unknown' },
    ],
  },
  {
    key: 'obtain_method',
    field: 'obtain_method',
    label: 'Obtain Method',
    options: [
      { label: 'Anniversaries', value: 'Anniversaries' },
      { label: 'Collab', value: 'Collab' },
      { label: 'Contingency_Contract_Store', value: 'Contingency_Contract_Store' },
      { label: 'Credit_Store', value: 'Credit_Store' },
      { label: 'Event', value: 'Event' },
      { label: 'Game_Mode_Reward', value: 'Game_Mode_Reward' },
      { label: 'Gold_Blue_Certificate_Store', value: 'Gold_Blue_Certificate_Store' },
      { label: 'Headhunting', value: 'Headhunting' },
      { label: 'Kernel_Headhunting', value: 'Kernel_Headhunting' },
      { label: 'Limited_Headhunting', value: 'Limited_Headhunting' },
      { label: 'Pinboard_Missions', value: 'Pinboard_Missions' },
      { label: 'Pre-Registration', value: 'Pre-Registration' },
      { label: 'Recruitment', value: 'Recruitment' },
      { label: 'Red_Certificate_Store', value: 'Red_Certificate_Store' },
      { label: 'Standard_Headhunting', value: 'Standard_Headhunting' },
      { label: 'Story_Progress', value: 'Story_Progress' },
    ],
  },
  {
    key: 'skill_type',
    field: 'skill_type',
    label: 'Skill Type',
    options: [
      { label: 'Auto Recovery', value: 'Auto Recovery' },
      { label: 'Offensive Recovery', value: 'Offensive Recovery' },
      { label: 'Defensive Recovery', value: 'Defensive Recovery' },
      { label: 'Auto', value: 'Auto' },
      { label: 'Manual', value: 'Manual' },
      { label: 'Passive', value: 'Passive' },
      { label: 'Permanent', value: 'Permanent' },
      { label: 'Charges', value: 'Charges' },
      { label: 'Ammo', value: 'Ammo' },
      { label: 'Overcharge', value: 'Overcharge' },
      { label: 'Overload', value: 'Overload' },
      { label: 'Mana', value: 'Mana' },
      { label: 'Chanting', value: 'Chanting' },
      { label: 'Equipment Alteration', value: 'Equipment Alteration' },
    ],
  },
  {
    key: 'race',
    field: 'race',
    label: 'Race',
    options: [
      { label: 'Ægir', value: 'Ægir' },
      { label: 'Anasa', value: 'Anasa' },
      { label: 'Anaty', value: 'Anaty' },
      { label: 'Anura', value: 'Anura' },
      { label: 'Archosauria', value: 'Archosauria' },
      { label: 'Aslan', value: 'Aslan' },
      { label: 'Caprinae', value: 'Caprinae' },
      { label: 'Cautus', value: 'Cautus' },
      { label: 'Cerato', value: 'Cerato' },
      { label: 'Chimera', value: 'Chimera' },
      { label: 'Draco', value: 'Draco' },
      { label: 'Durin', value: 'Durin' },
      { label: 'Dwarf', value: 'Dwarf' },
      { label: 'Elafia', value: 'Elafia' },
      { label: 'Elf', value: 'Elf' },
      { label: 'Feline', value: 'Feline' },
      { label: 'Forte', value: 'Forte' },
      { label: 'Half-foot', value: 'Half-foot' },
      { label: 'Itra', value: 'Itra' },
      { label: 'Kuranta', value: 'Kuranta' },
      { label: 'Kylin', value: 'Kylin' },
      { label: 'Liberi', value: 'Liberi' },
      { label: 'Lung', value: 'Lung' },
      { label: 'Lupo', value: 'Lupo' },
      { label: 'Manticore', value: 'Manticore' },
      { label: 'Oni', value: 'Oni' },
      { label: 'Perro', value: 'Perro' },
      { label: 'Petram', value: 'Petram' },
      { label: 'Phidia', value: 'Phidia' },
      { label: 'Pilosa', value: 'Pilosa' },
      { label: 'Rebbah', value: 'Rebbah' },
      { label: 'Reproba', value: 'Reproba' },
      { label: 'Robot', value: 'Robot' },
      { label: 'Sankta', value: 'Sankta' },
      { label: 'Sarkaz', value: 'Sarkaz' },
      { label: 'Savra', value: 'Savra' },
      { label: 'Tall-man', value: 'Tall-man' },
      { label: 'Undisclosed', value: 'Undisclosed' },
      { label: 'Unknown', value: 'Unknown' },
      { label: 'Ursus', value: 'Ursus' },
      { label: 'Vouivre', value: 'Vouivre' },
      { label: 'Vulpo', value: 'Vulpo' },
      { label: 'Zalak', value: 'Zalak' },
    ],
  },
  {
    key: 'faction',
    field: 'faction',
    label: 'Faction',
    options: [
      { label: 'Abyssal Hunters', value: 'Abyssal Hunters' },
      { label: 'Ægir', value: 'Ægir' },
      { label: 'Ave Mujica', value: 'Ave Mujica' },
      { label: 'Babel', value: 'Babel' },
      { label: 'Blacksteel', value: 'Blacksteel' },
      { label: 'Bolívar', value: 'Bolívar' },
      { label: 'Chiave\'s Gang', value: 'Chiave\'s Gang' },
      { label: 'Columbia', value: 'Columbia' },
      { label: 'Elite Op', value: 'Elite Op' },
      { label: 'Followers', value: 'Followers' },
      { label: 'Glasgow', value: 'Glasgow' },
      { label: 'Higashi', value: 'Higashi' },
      { label: 'Iberia', value: 'Iberia' },
      { label: 'Karlan Trade', value: 'Karlan Trade' },
      { label: 'Kazimierz', value: 'Kazimierz' },
      { label: 'Kjerag', value: 'Kjerag' },
      { label: 'Laios\'s Party', value: 'Laios\'s Party' },
      { label: 'Laterano', value: 'Laterano' },
      { label: 'Lee\'s Detective Agency', value: 'Lee\'s Detective Agency' },
      { label: 'Leithanien', value: 'Leithanien' },
      { label: 'Lungmen', value: 'Lungmen' },
      { label: 'Lungmen Guard Department', value: 'Lungmen Guard Department' },
      { label: 'Minos', value: 'Minos' },
      { label: 'Op A4', value: 'Op A4' },
      { label: 'Op Reserve A1', value: 'Op Reserve A1' },
      { label: 'Op Reserve A4', value: 'Op Reserve A4' },
      { label: 'Op Reserve A6', value: 'Op Reserve A6' },
      { label: 'Penguin Logistics', value: 'Penguin Logistics' },
      { label: 'Pinus Sylvestris', value: 'Pinus Sylvestris' },
      { label: 'Rhine Lab', value: 'Rhine Lab' },
      { label: 'Rhodes Island', value: 'Rhodes Island' },
      { label: 'Rim Billiton', value: 'Rim Billiton' },
      { label: 'S.W.E.E.P.', value: 'S.W.E.E.P.' },
      { label: 'Sami', value: 'Sami' },
      { label: 'Sargon', value: 'Sargon' },
      { label: 'Siesta', value: 'Siesta' },
      { label: 'Siracusa', value: 'Siracusa' },
      { label: 'Sui', value: 'Sui' },
      { label: 'Tara', value: 'Tara' },
      { label: 'Team Rainbow', value: 'Team Rainbow' },
      { label: 'Ursus', value: 'Ursus' },
      { label: 'Ursus Student Self-Governing Group', value: 'Ursus Student Self-Governing Group' },
      { label: 'Victoria', value: 'Victoria' },
      { label: 'Yan', value: 'Yan' },
    ],
  },
  {
    key: 'sub_faction',
    field: 'sub_faction',
    label: 'Sub Faction',
    options: [
      { label: 'Ægir', value: 'Ægir' },
      { label: 'Bolívar', value: 'Bolívar' },
      { label: 'Columbia', value: 'Columbia' },
      { label: 'Followers', value: 'Followers' },
      { label: 'Glasgow', value: 'Glasgow' },
      { label: 'Higashi', value: 'Higashi' },
      { label: 'Iberia', value: 'Iberia' },
      { label: 'Karlan Trade', value: 'Karlan Trade' },
      { label: 'Kazimierz', value: 'Kazimierz' },
      { label: 'Kazimierz , Leithanien', value: 'Kazimierz , Leithanien' },
      { label: 'Kjerag', value: 'Kjerag' },
      { label: 'Laterano', value: 'Laterano' },
      { label: 'Leithanien', value: 'Leithanien' },
      { label: 'Lungmen , Penguin Logistics', value: 'Lungmen , Penguin Logistics' },
      { label: 'Minos', value: 'Minos' },
      { label: 'Rhodes Island', value: 'Rhodes Island' },
      { label: 'Rim Billiton', value: 'Rim Billiton' },
      { label: 'Sargon', value: 'Sargon' },
      { label: 'Siracusa', value: 'Siracusa' },
      { label: 'Tara', value: 'Tara' },
      { label: 'Ursus', value: 'Ursus' },
      { label: 'Victoria', value: 'Victoria' },
      { label: 'Yan', value: 'Yan' },
      { label: 'Yan , Victoria', value: 'Yan , Victoria' },
    ],
  },
  {
    key: 'damage_type',
    field: 'damage_type',
    label: 'Damage Type',
    options: [
      { label: 'Arts', value: 'Arts' },
      { label: 'Burn', value: 'Burn' },
      { label: 'Corrosion', value: 'Corrosion' },
      { label: 'Elemental', value: 'Elemental' },
      { label: 'Healing', value: 'Healing' },
      { label: 'Necrosis', value: 'Necrosis' },
      { label: 'Nervous Impairment', value: 'Nervous Impairment' },
      { label: 'Physical', value: 'Physical' },
      { label: 'True', value: 'True' },
    ],
  },
  {
    key: 'illustrator',
    field: 'illustrator',
    label: 'Illustrator',
    options: [
      { label: '〇亻', value: '〇亻' },
      { label: '3MO', value: '3MO' },
      { label: 'AerialB', value: 'AerialB' },
      { label: 'alchemaniac', value: 'alchemaniac' },
      { label: 'Anisotropy', value: 'Anisotropy' },
      { label: 'Anmi', value: 'Anmi' },
      { label: 'Ask', value: 'Ask' },
      { label: 'aZLing4', value: 'aZLing4' },
      { label: 'azuタロウ', value: 'azuタロウ' },
      { label: 'Bkub Okawa', value: 'Bkub Okawa' },
      { label: 'Cenm0', value: 'Cenm0' },
      { label: 'Chi4', value: 'Chi4' },
      { label: 'Chuzenji', value: 'Chuzenji' },
      { label: 'deel', value: 'deel' },
      { label: 'Horin', value: 'Horin' },
      { label: 'hou', value: 'hou' },
      { label: 'HUG', value: 'HUG' },
      { label: 'infukun', value: 'infukun' },
      { label: 'IRIS_口艺', value: 'IRIS_口艺' },
      { label: 'Iritoa', value: 'Iritoa' },
      { label: 'Jacknife', value: 'Jacknife' },
      { label: 'kan', value: 'kan' },
      { label: 'KENTllaall', value: 'KENTllaall' },
      { label: 'kirine', value: 'kirine' },
      { label: 'Kumatangent', value: 'Kumatangent' },
      { label: 'KuroBlood', value: 'KuroBlood' },
      { label: 'LAL!ROLE', value: 'LAL!ROLE' },
      { label: 'Lanzi', value: 'Lanzi' },
      { label: 'Liduke', value: 'Liduke' },
      { label: 'Liyu黎', value: 'Liyu黎' },
      { label: 'LLC', value: 'LLC' },
      { label: 'LM7', value: 'LM7' },
      { label: 'Lowro', value: 'Lowro' },
      { label: 'Lpip', value: 'Lpip' },
      { label: 'M1917史密斯维森', value: 'M1917史密斯维森' },
      { label: 'M9nokuro', value: 'M9nokuro' },
      { label: 'Mag42', value: 'Mag42' },
      { label: 'min', value: 'min' },
      { label: 'Nagu', value: 'Nagu' },
      { label: 'Namie', value: 'Namie' },
      { label: 'neco', value: 'neco' },
      { label: 'nineo', value: 'nineo' },
      { label: 'NOCO', value: 'NOCO' },
      { label: 'NoriZC', value: 'NoriZC' },
      { label: 'Peachy Miruku', value: 'Peachy Miruku' },
      { label: 'RAN', value: 'RAN' },
      { label: 'RAYVON', value: 'RAYVON' },
      { label: 'REALMBW', value: 'REALMBW' },
      { label: 'redjuice', value: 'redjuice' },
      { label: 'SculLhunter', value: 'SculLhunter' },
      { label: 'Sho', value: 'Sho' },
      { label: 'Shō', value: 'Shō' },
      { label: 'Skade', value: 'Skade' },
      { label: 'small_ryuzaki', value: 'small_ryuzaki' },
      { label: 'STAR影法师', value: 'STAR影法师' },
      { label: 'Studio Montagne', value: 'Studio Montagne' },
      { label: 'TEAM EXPNDR', value: 'TEAM EXPNDR' },
      { label: 'toast', value: 'toast' },
      { label: 'TOKI', value: 'TOKI' },
      { label: 'TOMATO', value: 'TOMATO' },
      { label: 'TrNyteal', value: 'TrNyteal' },
      { label: 'Ubisoft', value: 'Ubisoft' },
      { label: 'umo_yszx', value: 'umo_yszx' },
      { label: 'U介', value: 'U介' },
      { label: 'WincalBlanke', value: 'WincalBlanke' },
      { label: 'YUJI', value: 'YUJI' },
      { label: 'Yukuso', value: 'Yukuso' },
      { label: 'アシマ', value: 'アシマ' },
      { label: 'おぐち', value: 'おぐち' },
      { label: 'およ', value: 'およ' },
      { label: 'カワグチ', value: 'カワグチ' },
      { label: 'せんむ', value: 'せんむ' },
      { label: 'ヌードル', value: 'ヌードル' },
      { label: 'れおえん', value: 'れおえん' },
      { label: '一千', value: '一千' },
      { label: '一立里子', value: '一立里子' },
      { label: '三目YYB', value: '三目YYB' },
      { label: '上埜', value: '上埜' },
      { label: '下野宏铭', value: '下野宏铭' },
      { label: '九日九号', value: '九日九号' },
      { label: '二开', value: '二开' },
      { label: '二色こぺ', value: '二色こぺ' },
      { label: '伍秋秋秋秋', value: '伍秋秋秋秋' },
      { label: '伍秋秋秋秋秋', value: '伍秋秋秋秋秋' },
      { label: '咩煲', value: '咩煲' },
      { label: '唯@W', value: '唯@W' },
      { label: '嘎嘎人', value: '嘎嘎人' },
      { label: '多元菌', value: '多元菌' },
      { label: '将', value: '将' },
      { label: '尾鱼', value: '尾鱼' },
      { label: '山x2', value: '山x2' },
      { label: '幻象黑兔', value: '幻象黑兔' },
      { label: '戏言咸咸', value: '戏言咸咸' },
      { label: '我妻洛酱', value: '我妻洛酱' },
      { label: '我妻洛醬', value: '我妻洛醬' },
      { label: '折射镜', value: '折射镜' },
      { label: '抽象Rotate', value: '抽象Rotate' },
      { label: '斑雀', value: '斑雀' },
      { label: '时辰', value: '时辰' },
      { label: '松尾省吾', value: '松尾省吾' },
      { label: '板板', value: '板板' },
      { label: '树豚', value: '树豚' },
      { label: '水滴鱼', value: '水滴鱼' },
      { label: '海猫络合物', value: '海猫络合物' },
      { label: '渣念', value: '渣念' },
      { label: '温泉瓜', value: '温泉瓜' },
      { label: '熊太', value: '熊太' },
      { label: '百慕大飞鱼', value: '百慕大飞鱼' },
      { label: '直立行走', value: '直立行走' },
      { label: '科学', value: '科学' },
      { label: '竜崎いち', value: '竜崎いち' },
      { label: '红色彗星', value: '红色彗星' },
      { label: '织布机loom', value: '织布机loom' },
      { label: '臼', value: '臼' },
      { label: '色塩', value: '色塩' },
      { label: '藻', value: '藻' },
      { label: '虎三', value: '虎三' },
      { label: '虬墨一型', value: '虬墨一型' },
      { label: '谜肘', value: '谜肘' },
      { label: '赤岸K', value: '赤岸K' },
      { label: '轟将', value: '轟将' },
      { label: '过失帝国', value: '过失帝国' },
      { label: '野崎つばた', value: '野崎つばた' },
      { label: '釜飯轟々丸', value: '釜飯轟々丸' },
      { label: '阿鬼', value: '阿鬼' },
      { label: '香煎蟹黄', value: '香煎蟹黄' },
      { label: '鸭', value: '鸭' },
      { label: '黒星紅白', value: '黒星紅白' },
    ],
  },
  {
    key: 'tag',
    field: 'tag',
    label: 'Tag',
    options: [
      { label: 'afk', value: 'afk' },
      { label: 'ammo_based', value: 'ammo_based' },
      { label: 'atk_buff', value: 'atk_buff' },
      { label: 'atk_down_debuff', value: 'atk_down_debuff' },
      { label: 'attack_interval_reduction', value: 'attack_interval_reduction' },
      { label: 'block_count_aoe', value: 'block_count_aoe' },
      { label: 'block_increase', value: 'block_increase' },
      { label: 'burst', value: 'burst' },
      { label: 'counter', value: 'counter' },
      { label: 'damage_amp', value: 'damage_amp' },
      { label: 'damage_return', value: 'damage_return' },
      { label: 'dmg_multiplier', value: 'dmg_multiplier' },
      { label: 'dot', value: 'dot' },
      { label: 'elemental_damage', value: 'elemental_damage' },
      { label: 'enemy_def_down', value: 'enemy_def_down' },
      { label: 'enemy_res_down', value: 'enemy_res_down' },
      { label: 'enmity', value: 'enmity' },
      { label: 'friendly_fire', value: 'friendly_fire' },
      { label: 'gives_invis_or_camo', value: 'gives_invis_or_camo' },
      { label: 'has_afk_skill', value: 'has_afk_skill' },
      { label: 'has_atk_scaling_or_multiplier', value: 'has_atk_scaling_or_multiplier' },
      { label: 'has_fragile', value: 'has_fragile' },
      { label: 'has_self_atk_buff', value: 'has_self_atk_buff' },
      { label: 'has_summons', value: 'has_summons' },
      { label: 'helidrop', value: 'helidrop' },
      { label: 'hp_barrier', value: 'hp_barrier' },
      { label: 'ignore_def', value: 'ignore_def' },
      { label: 'invis_reveal', value: 'invis_reveal' },
      { label: 'levitate', value: 'levitate' },
      { label: 'limited_operator', value: 'limited_operator' },
      { label: 'low_dp_cost', value: 'low_dp_cost' },
      { label: 'lower_taunt', value: 'lower_taunt' },
      { label: 'melee_unit_can_hit_air', value: 'melee_unit_can_hit_air' },
      { label: 'multi_attack', value: 'multi_attack' },
      { label: 'non_healing_subclass_healing', value: 'non_healing_subclass_healing' },
      { label: 'non_puller_pusher_shift', value: 'non_puller_pusher_shift' },
      { label: 'other_aspd_buff', value: 'other_aspd_buff' },
      { label: 'passive_healing', value: 'passive_healing' },
      { label: 'redeploy_manipulation', value: 'redeploy_manipulation' },
      { label: 'rng_based', value: 'rng_based' },
      { label: 'robot', value: 'robot' },
      { label: 'sanctuary_or_damage_reduction', value: 'sanctuary_or_damage_reduction' },
      { label: 'self_aspd_buff', value: 'self_aspd_buff' },
      { label: 'self_healing', value: 'self_healing' },
      { label: 'self_lose_hp', value: 'self_lose_hp' },
      { label: 'self_or_ally_def_buff', value: 'self_or_ally_def_buff' },
      { label: 'sp_battery', value: 'sp_battery' },
      { label: 'status_cleanse_or_resist', value: 'status_cleanse_or_resist' },
      { label: 'taunt', value: 'taunt' },
      { label: 'true_aoe', value: 'true_aoe' },
      { label: 'welfare', value: 'welfare' },
      { label: 'zero_block', value: 'zero_block' },
    ],
  },
  {
    key: 'status',
    field: 'status',
    label: 'Status',
    options: [
      { label: 'bind', value: 'bind' },
      { label: 'fear', value: 'fear' },
      { label: 'frighten', value: 'frighten' },
      { label: 'levitate', value: 'levitate' },
      { label: 'sleep', value: 'sleep' },
      { label: 'stun', value: 'stun' },
    ],
  },
  {
    key: 'elemental_affliction',
    field: 'elemental_affliction',
    label: 'Elemental Affliction',
    options: [
      { label: 'burn', value: 'burn' },
      { label: 'corrosion', value: 'corrosion' },
      { label: 'necrosis', value: 'necrosis' },
      { label: 'nervous_impairment', value: 'nervous_impairment' },
    ],
  },
];
